const fs = require('fs');
const path = require('path');

const dirs = [
  'public/geojson',
  'public/icons',
  'public/images',
  'src/api',
  'src/assets',
  'src/components/common',
  'src/components/map',
  'src/components/navigation',
  'src/components/buildings',
  'src/components/stalls',
  'src/components/admin',
  'src/context',
  'src/hooks',
  'src/layouts',
  'src/pages',
  'src/routes',
  'src/services',
  'src/store',
  'src/styles',
  'src/types',
  'src/utils',
];

dirs.forEach(d => fs.mkdirSync(path.join(__dirname, d), { recursive: true }));

const files = [
  'src/api/axios.ts',
  'src/api/navigation.ts',
  'src/api/gps.ts',
  'src/api/buildings.ts',
  'src/api/stalls.ts',
  'src/api/admin.ts',
  'src/api/search.ts',
  'src/components/common/Navbar.tsx',
  'src/components/common/Sidebar.tsx',
  'src/components/common/SearchBar.tsx',
  'src/components/common/Loader.tsx',
  'src/components/common/BottomSheet.tsx',
  'src/components/common/FloatingActionButton.tsx',
  'src/components/common/Toast.tsx',
  'src/components/common/Modal.tsx',
  'src/components/common/Skeleton.tsx',
  'src/components/map/CampusMap.tsx',
  'src/components/map/UserLocation.tsx',
  'src/components/map/RoutePolyline.tsx',
  'src/components/map/BuildingLayer.tsx',
  'src/components/map/WalkwayLayer.tsx',
  'src/components/map/EntranceLayer.tsx',
  'src/components/map/GateLayer.tsx',
  'src/components/map/ParkingLayer.tsx',
  'src/components/map/StallLayer.tsx',
  'src/components/map/MarkerPopup.tsx',
  'src/components/map/Compass.tsx',
  'src/components/map/ScaleBar.tsx',
  'src/components/navigation/RoutePanel.tsx',
  'src/components/navigation/DirectionCard.tsx',
  'src/components/navigation/ETA.tsx',
  'src/components/navigation/Distance.tsx',
  'src/components/navigation/StartButton.tsx',
  'src/components/navigation/StopButton.tsx',
  'src/components/buildings/BuildingCard.tsx',
  'src/components/buildings/BuildingPopup.tsx',
  'src/components/buildings/DepartmentList.tsx',
  'src/components/stalls/StallCard.tsx',
  'src/components/stalls/StallPopup.tsx',
  'src/components/stalls/CategoryFilter.tsx',
  'src/components/admin/Dashboard.tsx',
  'src/components/admin/AddBuilding.tsx',
  'src/components/admin/AddStall.tsx',
  'src/components/admin/EditNode.tsx',
  'src/components/admin/EditEdge.tsx',
  'src/components/admin/UploadGeoJSON.tsx',
  'src/pages/Home.tsx',
  'src/pages/Map.tsx',
  'src/pages/Search.tsx',
  'src/pages/Navigation.tsx',
  'src/pages/Buildings.tsx',
  'src/pages/BuildingDetails.tsx',
  'src/pages/Stalls.tsx',
  'src/pages/StallDetails.tsx',
  'src/pages/Events.tsx',
  'src/pages/Admin.tsx',
  'src/pages/Settings.tsx',
];

files.forEach(f => fs.writeFileSync(path.join(__dirname, f), ''));
